### ISSUE TITLE
Wrong branch name in documentation workflow

### ISSUE THREAD

**Issue by hiker** [MetOffice/fab#321]
https://github.com/MetOffice/fab/pull/316 contained an incorrect branch name:
```
name: Build Documentation

on:
  push:
    branches:
      - 'main'
```
This should be `master` I'd guess.
